apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"datanode"},"name":"datanode","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"datanode"}},"template":{"metadata":{"labels":{"app":"datanode"}},"spec":{"containers":[{"args":["-c"," sleep 30; hdfs datanode "],"command":["/bin/bash"],"env":[{"name":"CORE_CONF_fs_defaultFS","value":"hdfs://namenode:9000"},{"name":"CORE_CONF_hadoop_tmp_dir","value":"/tmp/hadoop"},{"name":"HDFS_CONF_dfs_replication","value":"1"},{"name":"HDFS_CONF_dfs_datanode_data_dir","value":"/hadoop/dfs/data"},{"name":"HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check","value":"false"}],"image":"apache/hadoop:3.3.4","name":"datanode","ports":[{"containerPort":9864}],"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/hadoop/dfs/data","name":"datanode-data"}]}],"volumes":[{"emptyDir":{},"name":"datanode-data"}]}}}}
  creationTimestamp: "2025-05-31T10:13:30Z"
  generation: 2
  labels:
    app: datanode
  name: datanode
  namespace: default
  resourceVersion: "203983"
  uid: fc39d27f-d91c-4999-b2f6-7a7198309604
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datanode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datanode
    spec:
      containers:
      - args:
        - -c
        - ' sleep 30; hdfs datanode '
        command:
        - /bin/bash
        env:
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:9000
        - name: CORE_CONF_hadoop_tmp_dir
          value: /tmp/hadoop
        - name: HDFS_CONF_dfs_replication
          value: "1"
        - name: HDFS_CONF_dfs_datanode_data_dir
          value: /hadoop/dfs/data
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: "false"
        image: apache/hadoop:3.3.4
        imagePullPolicy: IfNotPresent
        name: datanode
        ports:
        - containerPort: 9864
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hadoop/dfs/data
          name: datanode-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: datanode-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-01T06:19:14Z"
    lastUpdateTime: "2025-06-01T06:19:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-01T06:41:59Z"
    lastUpdateTime: "2025-06-01T06:41:59Z"
    message: ReplicaSet "datanode-5f6d6786b" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
