apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"hive-metastore","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"hive-metastore"}},"template":{"metadata":{"labels":{"app":"hive-metastore"}},"spec":{"containers":[{"args":["--service","metastore"],"command":["/opt/hive/bin/hive"],"image":"apache/hive:3.1.3","name":"hive-metastore","ports":[{"containerPort":9083}],"volumeMounts":[{"mountPath":"/opt/hive/conf/hive-site.xml","name":"hive-site-config","subPath":"hive-site.xml"},{"mountPath":"/opt/hive/lib/postgresql-42.2.18.jar","name":"postgres-jdbc-driver","subPath":"postgresql-42.2.18.jar"}]}],"initContainers":[{"args":["echo \"Waiting for PostgreSQL...\"\nuntil pg_isready -h postgres-hue -p 5432 -U hue; do \n  echo \"Waiting...\"\n  sleep 5\ndone\necho \"PostgreSQL ready!\"\n"],"command":["sh","-c"],"image":"postgres:13","name":"wait-for-postgres"},{"args":["echo \"Waiting for Namenode...\"\nuntil nc -z namenode 8020; do\n  echo \"Namenode not ready, waiting...\"\n  sleep 5\ndone\necho \"Namenode is ready!\"\n"],"command":["sh","-c"],"image":"busybox:1.35","name":"wait-for-namenode"}],"volumes":[{"configMap":{"name":"hive-site-config"},"name":"hive-site-config"},{"configMap":{"name":"postgres-jdbc-driver"},"name":"postgres-jdbc-driver"}]}}}}
  creationTimestamp: "2025-05-31T17:08:15Z"
  generation: 1
  name: hive-metastore
  namespace: default
  resourceVersion: "209728"
  uid: 5981b433-bb2e-40ec-83af-c38923ce4018
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hive-metastore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hive-metastore
    spec:
      containers:
      - args:
        - --service
        - metastore
        command:
        - /opt/hive/bin/hive
        image: apache/hive:3.1.3
        imagePullPolicy: IfNotPresent
        name: hive-metastore
        ports:
        - containerPort: 9083
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/hive/conf/hive-site.xml
          name: hive-site-config
          subPath: hive-site.xml
        - mountPath: /opt/hive/lib/postgresql-42.2.18.jar
          name: postgres-jdbc-driver
          subPath: postgresql-42.2.18.jar
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - "echo \"Waiting for PostgreSQL...\"\nuntil pg_isready -h postgres-hue -p
          5432 -U hue; do \n  echo \"Waiting...\"\n  sleep 5\ndone\necho \"PostgreSQL
          ready!\"\n"
        command:
        - sh
        - -c
        image: postgres:13
        imagePullPolicy: IfNotPresent
        name: wait-for-postgres
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - |
          echo "Waiting for Namenode..."
          until nc -z namenode 8020; do
            echo "Namenode not ready, waiting..."
            sleep 5
          done
          echo "Namenode is ready!"
        command:
        - sh
        - -c
        image: busybox:1.35
        imagePullPolicy: IfNotPresent
        name: wait-for-namenode
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: hive-site-config
        name: hive-site-config
      - configMap:
          defaultMode: 420
          name: postgres-jdbc-driver
        name: postgres-jdbc-driver
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-31T17:08:15Z"
    lastUpdateTime: "2025-05-31T17:08:18Z"
    message: ReplicaSet "hive-metastore-7f9f5b7c8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T09:54:31Z"
    lastUpdateTime: "2025-06-01T09:54:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
