apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"hiveserver2","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"hiveserver2"}},"template":{"metadata":{"labels":{"app":"hiveserver2"}},"spec":{"containers":[{"args":["--service","hiveserver2"],"command":["/opt/hive/bin/hive"],"env":[{"name":"SERVICE_NAME","value":"hiveserver2"},{"name":"SERVICE_OPTS","value":"-Dhive.metastore.uris=thrift://hive-metastore:9083"}],"image":"apache/hive:3.1.3","name":"hiveserver2","ports":[{"containerPort":10000},{"containerPort":10002}]}]}}}}
  creationTimestamp: "2025-05-31T09:58:03Z"
  generation: 2
  name: hiveserver2
  namespace: default
  resourceVersion: "208140"
  uid: 7460110f-e65e-4954-8a3d-99082e18d828
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hiveserver2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hiveserver2
    spec:
      containers:
      - args:
        - --service
        - hiveserver2
        command:
        - /opt/hive/bin/hive
        env:
        - name: SERVICE_NAME
          value: hiveserver2
        - name: SERVICE_OPTS
          value: -Dhive.metastore.uris=thrift://hive-metastore:9083
        image: apache/hive:3.1.3
        imagePullPolicy: IfNotPresent
        name: hiveserver2
        ports:
        - containerPort: 10000
          protocol: TCP
        - containerPort: 10002
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-31T09:58:03Z"
    lastUpdateTime: "2025-05-31T10:21:18Z"
    message: ReplicaSet "hiveserver2-58d975488" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T09:26:48Z"
    lastUpdateTime: "2025-06-01T09:26:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
