apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: hue
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-05-31T06:54:12Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: Helm
    deployment: hue
  name: hue
  namespace: default
  resourceVersion: "202434"
  uid: eb2eb235-807e-47a4-9eda-cc90492ed195
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      pod: hue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 2cf29cd052936ec7dcb6fe0c7b6e95a7c8a199d33887720fffc680b9b9fb610f
        checksum/config-extra: 82449ce52e26d3fb34110efeba2d1aa0bf518bb90d06f7323dfdef2a18dadc1f
        checksum/config-hive: c58fde318bb6a33b9e6a641bf274df60c32a7e64955105389950e1ad00006bb8
        kubectl.kubernetes.io/restartedAt: "2025-05-31T16:27:57+05:30"
      creationTimestamp: null
      labels:
        pod: hue
    spec:
      containers:
      - image: gethue/hue:latest
        imagePullPolicy: Always
        name: hue
        ports:
        - containerPort: 8888
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /desktop/debug/is_alive
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/hue/desktop/conf/hue.ini
          name: hue-config
          subPath: hue.ini
        - mountPath: /etc/hive/conf/hive-site.xml
          name: hive-config-volume
          subPath: hive-site
      - image: gethue/nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/sites-available/hue
          name: nginx-config
          subPath: hue
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: hue-config-complete
        name: hue-config
      - configMap:
          defaultMode: 420
          name: hive-config
        name: hive-config-volume
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-config
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-05-31T07:21:46Z"
    lastUpdateTime: "2025-05-31T11:43:49Z"
    message: ReplicaSet "hue-6c9f67d454" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T06:20:35Z"
    lastUpdateTime: "2025-06-01T06:20:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
