apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"postgres-hue"},"name":"postgres-hue","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"postgres-hue"}},"template":{"metadata":{"labels":{"app":"postgres-hue"}},"spec":{"containers":[{"env":[{"name":"POSTGRES_USER","value":"hue"},{"name":"POSTGRES_PASSWORD","value":"huepassword"},{"name":"POSTGRES_DB","value":"hue"},{"name":"PGDATA","value":"/var/lib/postgresql/data/pgdata"}],"image":"postgres:13","name":"postgres-hue","ports":[{"containerPort":5432}],"resources":{"requests":{"cpu":"20m"}},"volumeMounts":[{"mountPath":"/var/lib/postgresql/data","name":"postgres-data"}]}],"volumes":[{"name":"postgres-data","persistentVolumeClaim":{"claimName":"postgres-pvc"}}]}}}}
  creationTimestamp: "2025-05-31T07:17:28Z"
  generation: 1
  labels:
    app: postgres-hue
  name: postgres-hue
  namespace: default
  resourceVersion: "202177"
  uid: 2b85f3d4-593e-43f1-bb90-6113530f6bdc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres-hue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-hue
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: hue
        - name: POSTGRES_PASSWORD
          value: huepassword
        - name: POSTGRES_DB
          value: hue
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:13
        imagePullPolicy: IfNotPresent
        name: postgres-hue
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-31T07:17:28Z"
    lastUpdateTime: "2025-05-31T07:18:05Z"
    message: ReplicaSet "postgres-hue-64795fd76c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T06:19:13Z"
    lastUpdateTime: "2025-06-01T06:19:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
