apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"postgres-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
      volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    creationTimestamp: "2025-05-31T07:17:28Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: postgres-pvc
    namespace: default
    resourceVersion: "157330"
    uid: 0e550bfc-65f9-4832-a2a6-258348e67384
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-0e550bfc-65f9-4832-a2a6-258348e67384
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
