apiVersion: v1
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://namenode:8020</value>
      </property>
      <property>
        <name>hadoop.tmp.dir</name>
        <value>/tmp/hadoop</value>
      </property>
    </configuration>
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"core-site.xml":"\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003cconfiguration\u003e\n  \u003cproperty\u003e\n    \u003cname\u003efs.defaultFS\u003c/name\u003e\n    \u003cvalue\u003ehdfs://namenode:8020\u003c/value\u003e\n  \u003c/property\u003e\n  \u003cproperty\u003e\n    \u003cname\u003ehadoop.tmp.dir\u003c/name\u003e\n    \u003cvalue\u003e/tmp/hadoop\u003c/value\u003e\n  \u003c/property\u003e\n\u003c/configuration\u003e\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"hadoop-config","namespace":"default"}}
  creationTimestamp: "2025-05-31T19:11:20Z"
  name: hadoop-config
  namespace: default
  resourceVersion: "200891"
  uid: af035cc3-e5b2-4308-a56c-b3f884276faf
