apiVersion: v1
data:
  hive-site: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>

    <!--
    <property>
      <name>hive.support.concurrency</name>
      <value>false</value>
      <description>Whether hive supports concurrency or not. A zookeeper instance must be up and running for the default hive lock manager to support read-write locks.</description>
    </property>
    -->

    </configuration>
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: hue
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-05-31T06:54:12Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: hive-config
  namespace: default
  resourceVersion: "155561"
  uid: 6e59c5af-1add-4eea-9c46-bdb56a0c8923
