apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"datanode"},"name":"datanode","namespace":"default"},"spec":{"ports":[{"name":"datanode","port":9864}],"selector":{"app":"datanode"},"type":"ClusterIP"}}
  creationTimestamp: "2025-05-31T10:13:30Z"
  labels:
    app: datanode
  name: datanode
  namespace: default
  resourceVersion: "195941"
  uid: 2b5755e1-c2c2-4744-adba-9ce1aa1f5d10
spec:
  clusterIP: 10.98.145.126
  clusterIPs:
  - 10.98.145.126
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: datanode
    port: 9864
    protocol: TCP
    targetPort: 9864
  selector:
    app: datanode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
