apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hiveserver2-service","namespace":"default"},"spec":{"ports":[{"name":"thrift","port":10000,"targetPort":10000},{"name":"web","port":10002,"targetPort":10002}],"selector":{"app":"hiveserver2"}}}
  creationTimestamp: "2025-05-31T09:58:03Z"
  name: hiveserver2-service
  namespace: default
  resourceVersion: "162149"
  uid: 0670aa1a-c913-4f09-9fcb-c4e3a231799c
spec:
  clusterIP: 10.111.0.16
  clusterIPs:
  - 10.111.0.16
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: web
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: hiveserver2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
