apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hiveserver2","namespace":"default"},"spec":{"ports":[{"name":"thrift","port":10000,"targetPort":10000},{"name":"web","port":10002,"targetPort":10002}],"selector":{"app":"hiveserver2"}}}
  creationTimestamp: "2025-05-31T10:13:31Z"
  name: hiveserver2
  namespace: default
  resourceVersion: "163635"
  uid: cd04e2f1-eb00-4a7b-90ae-2cfcbf8f5c1f
spec:
  clusterIP: 10.111.23.215
  clusterIPs:
  - 10.111.23.215
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: web
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: hiveserver2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
