apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hive-metastore","namespace":"default"},"spec":{"ports":[{"port":9083,"targetPort":9083}],"selector":{"app":"hive-metastore"}}}
  creationTimestamp: "2025-05-31T10:13:30Z"
  name: hive-metastore
  namespace: default
  resourceVersion: "163623"
  uid: 689534c3-6e9b-4676-9969-ac46d97bec24
spec:
  clusterIP: 10.105.44.152
  clusterIPs:
  - 10.105.44.152
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9083
    protocol: TCP
    targetPort: 9083
  selector:
    app: hive-metastore
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
