apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hue-complete","namespace":"default"},"spec":{"ports":[{"port":8888,"targetPort":8888}],"selector":{"app":"hue-complete"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-05-31T10:13:31Z"
  name: hue-complete
  namespace: default
  resourceVersion: "163657"
  uid: 301f239a-8898-4287-a4a8-2cc93ca2a178
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.32.51
  clusterIPs:
  - 10.98.32.51
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31619
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: hue-complete
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
