apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"livy-service","namespace":"default"},"spec":{"ports":[{"port":8998,"targetPort":8998}],"selector":{"app":"livy"}}}
  creationTimestamp: "2025-05-31T09:58:03Z"
  name: livy-service
  namespace: default
  resourceVersion: "162188"
  uid: af9b17bc-39b3-4d3a-91b5-4c338a6cf7c2
spec:
  clusterIP: 10.105.242.141
  clusterIPs:
  - 10.105.242.141
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8998
    protocol: TCP
    targetPort: 8998
  selector:
    app: livy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
