apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres-hue","namespace":"default"},"spec":{"ports":[{"port":5432,"protocol":"TCP","targetPort":5432}],"selector":{"app":"postgres-hue"}}}
  creationTimestamp: "2025-05-31T07:17:28Z"
  name: postgres-hue
  namespace: default
  resourceVersion: "157313"
  uid: 52b85de4-88f3-4451-8a91-32e9e33a8ecc
spec:
  clusterIP: 10.104.75.109
  clusterIPs:
  - 10.104.75.109
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-hue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
