apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"spark-master-service","namespace":"default"},"spec":{"ports":[{"name":"spark","port":7077,"targetPort":7077},{"name":"web","port":8080,"targetPort":8080}],"selector":{"app":"spark-master"}}}
  creationTimestamp: "2025-05-31T09:58:03Z"
  name: spark-master-service
  namespace: default
  resourceVersion: "162171"
  uid: 204624c2-1615-45b0-a05e-406f631e9c03
spec:
  clusterIP: 10.101.207.233
  clusterIPs:
  - 10.101.207.233
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: spark
    port: 7077
    protocol: TCP
    targetPort: 7077
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spark-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
