apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"spark-master","namespace":"default"},"spec":{"ports":[{"name":"web","port":8080,"targetPort":8080},{"name":"spark","port":7077,"targetPort":7077}],"selector":{"app":"spark-master"}}}
  creationTimestamp: "2025-05-31T10:13:30Z"
  name: spark-master
  namespace: default
  resourceVersion: "163604"
  uid: b606f81b-f016-4398-b989-134e572370f1
spec:
  clusterIP: 10.109.38.71
  clusterIPs:
  - 10.109.38.71
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: spark
    port: 7077
    protocol: TCP
    targetPort: 7077
  selector:
    app: spark-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
