apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-05-31T10:13:31Z"
  generateName: hiveserver2-58d975488-
  labels:
    app: hiveserver2
    pod-template-hash: 58d975488
  name: hiveserver2-58d975488-zjxmn
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hiveserver2-58d975488
    uid: e4b127df-a283-4a74-ae20-d9f9a1169e89
  resourceVersion: "208134"
  uid: 27e1a1e0-4fdb-4a0c-9fd4-29c9c7928665
spec:
  containers:
  - args:
    - --service
    - hiveserver2
    command:
    - /opt/hive/bin/hive
    env:
    - name: SERVICE_NAME
      value: hiveserver2
    - name: SERVICE_OPTS
      value: -Dhive.metastore.uris=thrift://hive-metastore:9083
    image: apache/hive:3.1.3
    imagePullPolicy: IfNotPresent
    name: hiveserver2
    ports:
    - containerPort: 10000
      protocol: TCP
    - containerPort: 10002
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kk2rt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-kk2rt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-01T06:19:10Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-05-31T10:13:31Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-01T09:26:48Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-01T09:26:48Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-05-31T10:13:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://670c686ce1fee666dcf0a9e57d19b4ced725566fe75a4ca8770aeca50c585f4b
    image: apache/hive:3.1.3
    imageID: docker-pullable://apache/hive@sha256:d102ba29ad07e93c303894896203a80b903c0001d80221f1cb9fea92dcac06e4
    lastState:
      terminated:
        containerID: docker://f2cbf6095195609473c1f3d7537a12237d0d2abfaa26975b3df1e1bf2c974020
        exitCode: 255
        finishedAt: "2025-06-01T09:26:46Z"
        reason: Error
        startedAt: "2025-06-01T07:22:19Z"
    name: hiveserver2
    ready: true
    restartCount: 23
    started: true
    state:
      running:
        startedAt: "2025-06-01T09:26:47Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kk2rt
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  phase: Running
  podIP: 10.244.0.149
  podIPs:
  - ip: 10.244.0.149
  qosClass: BestEffort
  startTime: "2025-05-31T10:13:31Z"
